/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.51
 * Generated at: 2020-03-16 08:36:57 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class _20_005fnav_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar", Long.valueOf(1584003304432L));
    _jspx_dependants.put("jar:file:/C:/_jsp/workspace/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/FinalBoard/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar!/META-INF/c.tld", Long.valueOf(1425946270000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("    <!-- *** NAVBAR ***\n");
      out.write(" _________________________________________________________ -->\n");
      out.write("\n");
      out.write("    <div class=\"navbar navbar-default yamm\" role=\"navigation\" id=\"navbar\">\n");
      out.write("        <div class=\"container\">\n");
      out.write("            <div class=\"navbar-header\">\n");
      out.write("\n");
      out.write("                <a class=\"navbar-brand home\" href=\"index.html\" data-animate-hover=\"bounce\">\n");
      out.write("                    <img src=\"resources/img/logo.png\" alt=\"Obaju logo\" class=\"hidden-xs\">\n");
      out.write("                    <img src=\"resources/img/logo-small.png\" alt=\"Obaju logo\" class=\"visible-xs\"><span class=\"sr-only\">Obaju - go to homepage</span>\n");
      out.write("                </a>\n");
      out.write("                <div class=\"navbar-buttons\">\n");
      out.write("                    <button type=\"button\" class=\"navbar-toggle\" data-toggle=\"collapse\" data-target=\"#navigation\">\n");
      out.write("                        <span class=\"sr-only\">Toggle navigation</span>\n");
      out.write("                        <i class=\"fa fa-align-justify\"></i>\n");
      out.write("                    </button>\n");
      out.write("                    <button type=\"button\" class=\"navbar-toggle\" data-toggle=\"collapse\" data-target=\"#search\">\n");
      out.write("                        <span class=\"sr-only\">Toggle search</span>\n");
      out.write("                        <i class=\"fa fa-search\"></i>\n");
      out.write("                    </button>\n");
      out.write("                    <a class=\"btn btn-default navbar-toggle\" href=\"basket.html\">\n");
      out.write("                        <i class=\"fa fa-shopping-cart\"></i>  <span class=\"hidden-xs\">3 items in cart</span>\n");
      out.write("                    </a>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("            <!--/.navbar-header -->\n");
      out.write("\n");
      out.write("            <div class=\"navbar-collapse collapse\" id=\"navigation\">\n");
      out.write("\n");
      out.write("                <ul class=\"nav navbar-nav navbar-left\">\n");
      out.write("                    <li class=\"active\"><a href=\"index.html\">Home</a>\n");
      out.write("                    </li>\n");
      out.write("                    <li class=\"dropdown yamm-fw\">\n");
      out.write("                        <a href=\"#\" class=\"dropdown-toggle\" data-toggle=\"dropdown\" data-hover=\"dropdown\" data-delay=\"200\">Men <b class=\"caret\"></b></a>\n");
      out.write("                        <ul class=\"dropdown-menu\">\n");
      out.write("                            <li>\n");
      out.write("                                <div class=\"yamm-content\">\n");
      out.write("                                    <div class=\"row\">\n");
      out.write("                                        <div class=\"col-sm-3\">\n");
      out.write("                                            <h5>Clothing</h5>\n");
      out.write("                                            <ul>\n");
      out.write("                                                <li><a href=\"category.html\">T-shirts</a>\n");
      out.write("                                                </li>\n");
      out.write("                                                <li><a href=\"category.html\">Shirts</a>\n");
      out.write("                                                </li>\n");
      out.write("                                                <li><a href=\"category.html\">Pants</a>\n");
      out.write("                                                </li>\n");
      out.write("                                                <li><a href=\"category.html\">Accessories</a>\n");
      out.write("                                                </li>\n");
      out.write("                                            </ul>\n");
      out.write("                                        </div>\n");
      out.write("                                        <div class=\"col-sm-3\">\n");
      out.write("                                            <h5>Shoes</h5>\n");
      out.write("                                            <ul>\n");
      out.write("                                                <li><a href=\"category.html\">Trainers</a>\n");
      out.write("                                                </li>\n");
      out.write("                                                <li><a href=\"category.html\">Sandals</a>\n");
      out.write("                                                </li>\n");
      out.write("                                                <li><a href=\"category.html\">Hiking shoes</a>\n");
      out.write("                                                </li>\n");
      out.write("                                                <li><a href=\"category.html\">Casual</a>\n");
      out.write("                                                </li>\n");
      out.write("                                            </ul>\n");
      out.write("                                        </div>\n");
      out.write("                                        <div class=\"col-sm-3\">\n");
      out.write("                                            <h5>Accessories</h5>\n");
      out.write("                                            <ul>\n");
      out.write("                                                <li><a href=\"category.html\">Trainers</a>\n");
      out.write("                                                </li>\n");
      out.write("                                                <li><a href=\"category.html\">Sandals</a>\n");
      out.write("                                                </li>\n");
      out.write("                                                <li><a href=\"category.html\">Hiking shoes</a>\n");
      out.write("                                                </li>\n");
      out.write("                                                <li><a href=\"category.html\">Casual</a>\n");
      out.write("                                                </li>\n");
      out.write("                                                <li><a href=\"category.html\">Hiking shoes</a>\n");
      out.write("                                                </li>\n");
      out.write("                                                <li><a href=\"category.html\">Casual</a>\n");
      out.write("                                                </li>\n");
      out.write("                                            </ul>\n");
      out.write("                                        </div>\n");
      out.write("                                        <div class=\"col-sm-3\">\n");
      out.write("                                            <h5>Featured</h5>\n");
      out.write("                                            <ul>\n");
      out.write("                                                <li><a href=\"category.html\">Trainers</a>\n");
      out.write("                                                </li>\n");
      out.write("                                                <li><a href=\"category.html\">Sandals</a>\n");
      out.write("                                                </li>\n");
      out.write("                                                <li><a href=\"category.html\">Hiking shoes</a>\n");
      out.write("                                                </li>\n");
      out.write("                                            </ul>\n");
      out.write("                                            <h5>Looks and trends</h5>\n");
      out.write("                                            <ul>\n");
      out.write("                                                <li><a href=\"category.html\">Trainers</a>\n");
      out.write("                                                </li>\n");
      out.write("                                                <li><a href=\"category.html\">Sandals</a>\n");
      out.write("                                                </li>\n");
      out.write("                                                <li><a href=\"category.html\">Hiking shoes</a>\n");
      out.write("                                                </li>\n");
      out.write("                                            </ul>\n");
      out.write("                                        </div>\n");
      out.write("                                    </div>\n");
      out.write("                                </div>\n");
      out.write("                                <!-- /.yamm-content -->\n");
      out.write("                            </li>\n");
      out.write("                        </ul>\n");
      out.write("                    </li>\n");
      out.write("\n");
      out.write("                    <li class=\"dropdown yamm-fw\">\n");
      out.write("                        <a href=\"#\" class=\"dropdown-toggle\" data-toggle=\"dropdown\" data-hover=\"dropdown\" data-delay=\"200\">Ladies <b class=\"caret\"></b></a>\n");
      out.write("                        <ul class=\"dropdown-menu\">\n");
      out.write("                            <li>\n");
      out.write("                                <div class=\"yamm-content\">\n");
      out.write("                                    <div class=\"row\">\n");
      out.write("                                        <div class=\"col-sm-3\">\n");
      out.write("                                            <h5>Clothing</h5>\n");
      out.write("                                            <ul>\n");
      out.write("                                                <li><a href=\"category.html\">T-shirts</a>\n");
      out.write("                                                </li>\n");
      out.write("                                                <li><a href=\"category.html\">Shirts</a>\n");
      out.write("                                                </li>\n");
      out.write("                                                <li><a href=\"category.html\">Pants</a>\n");
      out.write("                                                </li>\n");
      out.write("                                                <li><a href=\"category.html\">Accessories</a>\n");
      out.write("                                                </li>\n");
      out.write("                                            </ul>\n");
      out.write("                                        </div>\n");
      out.write("                                        <div class=\"col-sm-3\">\n");
      out.write("                                            <h5>Shoes</h5>\n");
      out.write("                                            <ul>\n");
      out.write("                                                <li><a href=\"category.html\">Trainers</a>\n");
      out.write("                                                </li>\n");
      out.write("                                                <li><a href=\"category.html\">Sandals</a>\n");
      out.write("                                                </li>\n");
      out.write("                                                <li><a href=\"category.html\">Hiking shoes</a>\n");
      out.write("                                                </li>\n");
      out.write("                                                <li><a href=\"category.html\">Casual</a>\n");
      out.write("                                                </li>\n");
      out.write("                                            </ul>\n");
      out.write("                                        </div>\n");
      out.write("                                        <div class=\"col-sm-3\">\n");
      out.write("                                            <h5>Accessories</h5>\n");
      out.write("                                            <ul>\n");
      out.write("                                                <li><a href=\"category.html\">Trainers</a>\n");
      out.write("                                                </li>\n");
      out.write("                                                <li><a href=\"category.html\">Sandals</a>\n");
      out.write("                                                </li>\n");
      out.write("                                                <li><a href=\"category.html\">Hiking shoes</a>\n");
      out.write("                                                </li>\n");
      out.write("                                                <li><a href=\"category.html\">Casual</a>\n");
      out.write("                                                </li>\n");
      out.write("                                                <li><a href=\"category.html\">Hiking shoes</a>\n");
      out.write("                                                </li>\n");
      out.write("                                                <li><a href=\"category.html\">Casual</a>\n");
      out.write("                                                </li>\n");
      out.write("                                            </ul>\n");
      out.write("                                            <h5>Looks and trends</h5>\n");
      out.write("                                            <ul>\n");
      out.write("                                                <li><a href=\"category.html\">Trainers</a>\n");
      out.write("                                                </li>\n");
      out.write("                                                <li><a href=\"category.html\">Sandals</a>\n");
      out.write("                                                </li>\n");
      out.write("                                                <li><a href=\"category.html\">Hiking shoes</a>\n");
      out.write("                                                </li>\n");
      out.write("                                            </ul>\n");
      out.write("                                        </div>\n");
      out.write("                                        <div class=\"col-sm-3\">\n");
      out.write("                                            <div class=\"banner\">\n");
      out.write("                                                <a href=\"#\">\n");
      out.write("                                                    <img src=\"img/banner.jpg\" class=\"img img-responsive\" alt=\"\">\n");
      out.write("                                                </a>\n");
      out.write("                                            </div>\n");
      out.write("                                            <div class=\"banner\">\n");
      out.write("                                                <a href=\"#\">\n");
      out.write("                                                    <img src=\"img/banner2.jpg\" class=\"img img-responsive\" alt=\"\">\n");
      out.write("                                                </a>\n");
      out.write("                                            </div>\n");
      out.write("                                        </div>\n");
      out.write("                                    </div>\n");
      out.write("                                </div>\n");
      out.write("                                <!-- /.yamm-content -->\n");
      out.write("                            </li>\n");
      out.write("                        </ul>\n");
      out.write("                    </li>\n");
      out.write("\n");
      out.write("                    <li class=\"dropdown yamm-fw\">\n");
      out.write("                        <a href=\"#\" class=\"dropdown-toggle\" data-toggle=\"dropdown\" data-hover=\"dropdown\" data-delay=\"200\">Template <b class=\"caret\"></b></a>\n");
      out.write("                        <ul class=\"dropdown-menu\">\n");
      out.write("                            <li>\n");
      out.write("                                <div class=\"yamm-content\">\n");
      out.write("                                    <div class=\"row\">\n");
      out.write("                                        <div class=\"col-sm-3\">\n");
      out.write("                                            <h5>Shop</h5>\n");
      out.write("                                            <ul>\n");
      out.write("                                                <li><a href=\"index.html\">Homepage</a>\n");
      out.write("                                                </li>\n");
      out.write("                                                <li><a href=\"category.html\">Category - sidebar left</a>\n");
      out.write("                                                </li>\n");
      out.write("                                                <li><a href=\"category-right.html\">Category - sidebar right</a>\n");
      out.write("                                                </li>\n");
      out.write("                                                <li><a href=\"category-full.html\">Category - full width</a>\n");
      out.write("                                                </li>\n");
      out.write("                                                <li><a href=\"detail.html\">Product detail</a>\n");
      out.write("                                                </li>\n");
      out.write("                                            </ul>\n");
      out.write("                                        </div>\n");
      out.write("                                        <div class=\"col-sm-3\">\n");
      out.write("                                            <h5>User</h5>\n");
      out.write("                                            <ul>\n");
      out.write("                                                <li><a href=\"register.html\">Register / login</a>\n");
      out.write("                                                </li>\n");
      out.write("                                                <li><a href=\"customer-orders.html\">Orders history</a>\n");
      out.write("                                                </li>\n");
      out.write("                                                <li><a href=\"customer-order.html\">Order history detail</a>\n");
      out.write("                                                </li>\n");
      out.write("                                                <li><a href=\"customer-wishlist.html\">Wishlist</a>\n");
      out.write("                                                </li>\n");
      out.write("                                                <li><a href=\"customer-account.html\">Customer account / change password</a>\n");
      out.write("                                                </li>\n");
      out.write("                                            </ul>\n");
      out.write("                                        </div>\n");
      out.write("                                        <div class=\"col-sm-3\">\n");
      out.write("                                            <h5>Order process</h5>\n");
      out.write("                                            <ul>\n");
      out.write("                                                <li><a href=\"basket.html\">Shopping cart</a>\n");
      out.write("                                                </li>\n");
      out.write("                                                <li><a href=\"checkout1.html\">Checkout - step 1</a>\n");
      out.write("                                                </li>\n");
      out.write("                                                <li><a href=\"checkout2.html\">Checkout - step 2</a>\n");
      out.write("                                                </li>\n");
      out.write("                                                <li><a href=\"checkout3.html\">Checkout - step 3</a>\n");
      out.write("                                                </li>\n");
      out.write("                                                <li><a href=\"checkout4.html\">Checkout - step 4</a>\n");
      out.write("                                                </li>\n");
      out.write("                                            </ul>\n");
      out.write("                                        </div>\n");
      out.write("                                        <div class=\"col-sm-3\">\n");
      out.write("                                            <h5>Pages and blog</h5>\n");
      out.write("                                            <ul>\n");
      out.write("                                                <li><a href=\"blog.html\">Blog listing</a>\n");
      out.write("                                                </li>\n");
      out.write("                                                <li><a href=\"post.html\">Blog Post</a>\n");
      out.write("                                                </li>\n");
      out.write("                                                <li><a href=\"faq.html\">FAQ</a>\n");
      out.write("                                                </li>\n");
      out.write("                                                <li><a href=\"text.html\">Text page</a>\n");
      out.write("                                                </li>\n");
      out.write("                                                <li><a href=\"text-right.html\">Text page - right sidebar</a>\n");
      out.write("                                                </li>\n");
      out.write("                                                <li><a href=\"404.html\">404 page</a>\n");
      out.write("                                                </li>\n");
      out.write("                                                <li><a href=\"contact.html\">Contact</a>\n");
      out.write("                                                </li>\n");
      out.write("                                            </ul>\n");
      out.write("                                        </div>\n");
      out.write("                                    </div>\n");
      out.write("                                </div>\n");
      out.write("                                <!-- /.yamm-content -->\n");
      out.write("                            </li>\n");
      out.write("                        </ul>\n");
      out.write("                    </li>\n");
      out.write("                </ul>\n");
      out.write("\n");
      out.write("            </div>\n");
      out.write("            <!--/.nav-collapse -->\n");
      out.write("\n");
      out.write("            <div class=\"navbar-buttons\">\n");
      out.write("\n");
      out.write("                <div class=\"navbar-collapse collapse right\" id=\"basket-overview\">\n");
      out.write("                    <a href=\"basket.html\" class=\"btn btn-primary navbar-btn\"><i class=\"fa fa-shopping-cart\"></i><span class=\"hidden-sm\">3 items in cart</span></a>\n");
      out.write("                </div>\n");
      out.write("                <!--/.nav-collapse -->\n");
      out.write("\n");
      out.write("                <div class=\"navbar-collapse collapse right\" id=\"search-not-mobile\">\n");
      out.write("                    <button type=\"button\" class=\"btn navbar-btn btn-primary\" data-toggle=\"collapse\" data-target=\"#search\">\n");
      out.write("                        <span class=\"sr-only\">Toggle search</span>\n");
      out.write("                        <i class=\"fa fa-search\"></i>\n");
      out.write("                    </button>\n");
      out.write("                </div>\n");
      out.write("\n");
      out.write("            </div>\n");
      out.write("\n");
      out.write("            <div class=\"collapse clearfix\" id=\"search\">\n");
      out.write("\n");
      out.write("                <form class=\"navbar-form\" role=\"search\">\n");
      out.write("                    <div class=\"input-group\">\n");
      out.write("                        <input type=\"text\" class=\"form-control\" placeholder=\"Search\">\n");
      out.write("                        <span class=\"input-group-btn\">\n");
      out.write("\n");
      out.write("\t\t\t<button type=\"submit\" class=\"btn btn-primary\"><i class=\"fa fa-search\"></i></button>\n");
      out.write("\n");
      out.write("\t\t    </span>\n");
      out.write("                    </div>\n");
      out.write("                </form>\n");
      out.write("\n");
      out.write("            </div>\n");
      out.write("            <!--/.nav-collapse -->\n");
      out.write("\n");
      out.write("        </div>\n");
      out.write("        <!-- /.container -->\n");
      out.write("    </div>\n");
      out.write("    <!-- /#navbar -->\n");
      out.write("    \n");
      out.write("    <!-- *** NAVBAR END *** -->\n");
      out.write("    ");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
