CREATE TABLE SPRINGDB.TBL_PRODUCT (
	PNO NUMBER NOT NULL,
	TITLE VARCHAR2(200) NOT NULL,
	WRITER VARCHAR2(100) NOT NULL,
	CONTENT VARCHAR2(2000) NOT NULL,
	READCOUNT VARCHAR2(100) DEFAULT 0,
	MODDB DATE DEFAULT sysdate,
	REGDB DATE DEFAULT sysdate,
	IMGFILE VARCHAR2(2000)
);


ALTER TABLE SPRINGDB.TBL_PRODUCT
ADD CONSTRAINT TBL_PRODUCT_PK PRIMARY KEY (PNO)
ENABLE;


CREATE SEQUENCE SPRINGDB.SEQ_PRODUCT INCREMENT BY 1 MINVALUE 0 NOCYCLE NOCACHE NOORDER ;
